<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Laporan_kegiatan_model extends CI_Model
{

    public $table = 'laporan_kegiatan';
    public $id = 'id_laporan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function hitung()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->num_rows();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    public function total_rows($q = null, $tgl_awal = null, $tgl_akhir = null)
    {
        $this->db->from('laporan_kegiatan');

        if ($q) {
            $this->db->group_start();
            $this->db->like('id_perencanaan', $q);
            $this->db->like('id_proposal', $q);
            $this->db->or_like('tgl_kegiatan', $q);
            $this->db->or_like('laporan_kegiatan', $q);
            $this->db->or_like('jenis_kegiatan', $q);
            $this->db->group_end();
        }

        if ($tgl_awal && $tgl_akhir) {
            $this->db->where('tgl_kegiatan >=', $tgl_awal);
            $this->db->where('tgl_kegiatan <=', $tgl_akhir);
        }

        return $this->db->count_all_results();
    }

    
    public function filterDataByDate($start_date, $end_date) {
       
        $this->db->query("Select * from laporan_kegiatan where tgl_kegiatan >= ".$start_date." and tgl_kegiatan <=".$end_date)->result();
        
    }
    

    public function get_limit_data($limit, $start = 0, $q = null, $tgl_awal = null, $tgl_akhir = null)
    {
        $this->db->order_by('id_laporan', 'DESC');

        if ($q) {
            $this->db->group_start();
            $this->db->like('id_perencanaan', $q);
            $this->db->like('id_proposal', $q);
            $this->db->or_like('tgl_kegiatan', $q);
            $this->db->or_like('laporan_kegiatan', $q);
            $this->db->or_like('jenis_kegiatan', $q);
            $this->db->group_end();
        }

        if ($tgl_awal && $tgl_akhir) {
            $this->db->where('tgl_kegiatan >=', $tgl_awal);
            $this->db->where('tgl_kegiatan <=', $tgl_akhir);
        }

        return $this->db->get($this->table)->result();

    }

    //mengambil filter tanggal
    function get_laporan_kegiatan($start = 0, $q = NULL,$tanggal_awal,$tanggal_akhir) {
        $this->db->order_by($this->id, $this->order);
    $this->db->where('tgl_kegiatan >=',$tanggal_awal);
    $this->db->where('tgl_kegiatan <=',$tanggal_akhir);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Laporan_kegiatan_model.php */
/* Location: ./application/models/Laporan_kegiatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-22 09:49:07 */
/* http://harviacode.com */