<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pembuatan_disposisi_model extends CI_Model
{

    public $table = 'pembuatan_disposisi';
    public $id = 'id_disposisi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function hitung()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->num_rows();
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_disposisi', $q);
	$this->db->or_like('id_proposal', $q);
	$this->db->or_like('pengirim', $q);
	$this->db->or_like('kualifikasi', $q);
	$this->db->or_like('ditindak_lanjuti', $q);
	$this->db->or_like('catatan_khusus', $q);
	//$this->db->or_like('file_disposisi', $q);
	//$this->db->or_like('biaya_approve', $q);
	//$this->db->or_like('tgl_kegiatan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
            $this->db->select('p.*,k.kode_proposal, k.nama_lengkap');
            $this->db->from('pembuatan_disposisi p');
            $this->db->join('proposal k', 'k.id_proposal = p.id_proposal');

              
        
        $this->db->order_by('p.id_disposisi', $this->order);
	$this->db->or_like('p.id_proposal', $q);
	$this->db->or_like('p.pengirim', $q);
	$this->db->or_like('p.kualifikasi', $q);
	$this->db->or_like('p.ditindak_lanjuti', $q);
	$this->db->or_like('p.catatan_khusus', $q);
	//$this->db->or_like('file_disposisi', $q);
	//$this->db->or_like('p.biaya_approve', $q);
	//$this->db->or_like('p.tgl_kegiatan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pembuatan_disposisi_model.php */
/* Location: ./application/models/Pembuatan_disposisi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-24 20:15:22 */
/* http://harviacode.com */