<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Perencanaan_kegiatan_model extends CI_Model
{

    public $table = 'perencanaan_kegiatan';
    public $id = 'id_perencanaan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_perencanaan', $q);
	$this->db->or_like('nama_lengkap', $q);
	$this->db->or_like('id_proposal', $q);
	$this->db->or_like('tempat_kegiatan', $q);
    $this->db->or_like('tgl_kegiatan', $q);
	$this->db->or_like('biaya_approve', $q);
	$this->db->or_like('rekening_pospay', $q);
	$this->db->or_like('rapat_kegiatan', $q);
	$this->db->or_like('status_kegiatan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search

        function get_limit_data($limit, $start = 0, $q = NULL) {
            $this->db->select('e.*,k.id_proposal, k.nama_lengkap');
            $this->db->from('perencanaan_kegiatan e');
            $this->db->join('proposal k', 'k.id_proposal = e.id_proposal'); 
            if($_SESSION['hak_akses'] !='Admin'){
                $this->db->where('k.nama_lengkap',$this->session->userdata('nama_lengkap'));
            }
           
            // $this->db->where('p.rekening_pospay',$this->session->userdata('rekening_pospay'));
        $this->db->order_by('e.id_perencanaan', $this->order);
	// $this->db->or_like('e.nama_lengkap', $q);
	// $this->db->or_like('e.id_proposal', $q);
	// $this->db->or_like('e.tempat_kegiatan', $q);
	// $this->db->or_like('e.biaya_approve', $q);
	// $this->db->or_like('e.rekening_pospay', $q);
	// $this->db->or_like('e.rapat_kegiatan', $q);
	// $this->db->or_like('e.status_kegiatan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Perencanaan_kegiatan_model.php */
/* Location: ./application/models/Perencanaan_kegiatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-18 23:32:56 */
/* http://harviacode.com */