<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Proposal_model extends CI_Model
{

    public $table = 'proposal';
    public $id = 'id_proposal';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function hitung()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->num_rows();
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_proposal', $q);
	$this->db->or_like('kode_proposal', $q);
	$this->db->or_like('nama_lengkap', $q);
	$this->db->or_like('Jenis_kegiatan', $q);
	$this->db->or_like('tanggal_terima', $q);
	$this->db->or_like('proposal', $q);
	$this->db->or_like('surat_pengantar', $q);
    $this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_proposal', $q);
	$this->db->or_like('kode_proposal', $q);
	$this->db->or_like('nama_lengkap', $q);
	$this->db->or_like('Jenis_kegiatan', $q);
	$this->db->or_like('tanggal_terima', $q);
	$this->db->or_like('proposal', $q);
	$this->db->or_like('surat_pengantar', $q);
    $this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function get_max_id()
    {
        $this->db->select_max('id_proposal');
        $query = $this->db->get('proposal');
        $result = $query->row();
        return $result->id_proposal ? $result->id_proposal : 0;
    }

    public function get_recent_data($limit, $offset, $search = '')
    {
        $this->db->order_by('tanggal_terima', 'desc'); // Sort by 'tanggal_terima' field in descending order (most recent first)

        if ($search !== '') {
            // Assuming you have some search fields, adjust this part as per your needs
            $this->db->like('field_name', $search);
        }

        $query = $this->db->get('proposal', $limit, $offset);
        return $query->result();
    }


}

/* End of file Proposal_model.php */
/* Location: ./application/models/Proposal_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-18 23:32:57 */
/* http://harviacode.com */